fix compile error when using SBO as library with newer controller-runtime
redhat-developer/service-binding-operator pull request #1039
Opened 2021-10-01 17:41 UTC by pedjak

SBO uses currently controller-runtime 0.6.4 and there the admission webhook `Request` struct
uses v1beta1 API. Later controller-runtime versions use `v1` version, and this
turned to generate compile error when SBO is included as dependency in a project
using latest controller-runtime as well.

The root cause for the issue is that the admission webhook is part of `api` package,
and therefore needs to be complied even if not used in the project.

There is no reasons why the webhook code need to be a part of `api` package, and
the issue is fixed by moving it in separate `apis/webhooks` package.

Two new test projects are added so that we can catch regressions.

2021-10-01 22:35 UTC, pedjak commented on apis/webhooks/admision.go
> +package webhooks
done.

2021-10-04 10:10 UTC, baijum approved these changes
/lgtm

2021-10-04 12:24 UTC, sadlerap requested changes
Looks mostly good to me, just a few minor issues.

2021-10-04 12:24 UTC, sadlerap commented on test/library_test.go
> +	cmd := exec.Command("sh", "-c", "go mod download; go mod tidy; go build -o main")
If one of these commands returns an error, do we want to run successive commands?  For example, if `go mod download` or `go mod tidy` fails, building doesn't make sense, and I think we should short circuit.
```suggestion
	cmd := exec.Command("sh", "-c", "go mod download && go mod tidy && go build -o main")
```

2021-10-04 14:09 UTC, sadlerap approved these changes

2021-10-04 14:12 UTC, sadlerap commented
/lgtm

2021-10-04 14:15 UTC, sadlerap commented
/approve

2021-10-04 15:46 UTC, merged