Make sure to return nil value when there was an error
redhat-developer/service-binding-operator pull request #1079
Opened 2021-12-07 09:57 UTC by kadel

### Motivation
Saving service crd (`s.crd`) when there was an error while retrieving it (`s.CrdReader(s.groupVersionResource)`) can lead to `nil` pointer problems.

This was causing problem for odo when it tried to use SBO as a library.

### Changes

Return error and don't save crd to `s.crd`.

### Testing

Added a test that covers this scenario.

For further more details refer the CONTRIBUTING.md

2021-12-07 12:31 UTC, pedjak requested changes
looks good - we need just to tighten error assertion in the new test.

2021-12-07 12:31 UTC, pedjak commented on pkg/reconcile/pipeline/context/service/service_test.go
> +		Expect(err).To(HaveOccurred())
the error should occur and should be the very same that get return in line 100.

2021-12-07 13:09 UTC, pedjak approved these changes
/lgtm please squash commits

2021-12-08 10:12 UTC, kadel commented
> /lgtm please squash commits

done. thx for review.

2021-12-08 11:46 UTC, pedjak approved these changes
/lgtm
/approve

2021-12-08 12:14 UTC, merged