Enable annotations mapping to be optional
redhat-developer/service-binding-operator pull request #1161
Opened 2022-06-02 08:28 UTC by baijum

Fixes #1088

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#docs) 
  included if any changes are user facing
- [ ] [Tests](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#tests)
  included if any functionality added or changed. For bugfixes please include tests that can catch regressions
- [ ] All acceptance test scenarios included in the PR which verifies a bugfix or a requested feature reported by a non-member are tagged with `@external-feedback` tag.
- [ ] Follows the [commit message standard](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#commits)

2022-06-02 11:30 UTC, feloy commented
Do we need to add the `optional=true` option to the redis CRD annotation manually, or will it be added by the service binding operator?

2022-06-02 11:31 UTC, pmacik commented
/retest

2022-06-02 14:41 UTC, sadlerap requested changes
Mostly looks good to me, a few changes though:
- There are some warnings from the linter that need to be addressed.
- I would like to see some unit tests added.

2022-06-03 09:33 UTC, baijum commented
> Do we need to add the `optional=true` option to the redis CRD annotation manually, or will it be added by the service binding operator?

I have made that change in this PR.

2022-06-03 09:57 UTC, feloy commented
This PR will fix the original issue.  Thanks for this work
LGTM

2022-06-03 10:59 UTC, baijum commented
> * There are some warnings from the linter that need to be addressed.

Fixed.

> * I would like to see some unit tests added.

Done.

2022-06-09 12:08 UTC, baijum commented on test/acceptance/features/bindAppToServiceAnnotationsOptional.feature
> +    Scenario: Bind to the application with annotations and with missing non-optional source field to cause binding failure
Add a scenario with `optional=false` (feedback from commmunity call)

2022-06-13 09:27 UTC, baijum commented on test/acceptance/features/bindAppToServiceAnnotationsOptional.feature
> +    Scenario: Bind to the application with annotations and with missing non-optional source field to cause binding failure
Added the test case.

2022-06-13 20:05 UTC, sadlerap commented
/retest

2022-06-15 09:26 UTC, baijum commented
/retest

2022-06-15 10:00 UTC, pmacik commented
/retest

2022-06-15 11:34 UTC, baijum commented
/retest

2022-06-15 14:02 UTC, baijum commented
/retest

2022-06-15 18:32 UTC, sadlerap approved these changes
/lgtm

@Srivaralakshmi should probably take a look at the docs changes.

2022-06-15 19:26 UTC, pmacik commented
/hold

2022-06-16 04:54 UTC, pmacik commented
/retest

2022-06-23 10:50 UTC, Srivaralakshmi requested changes
@baijum Left my suggestions. PTAL.Thanks!

2022-06-24 01:38 UTC, baijum commented on docs/userguide/modules/exposing-binding-data/pages/adding-annotation.adoc
> +Sometimes a field may not exist in the target path. By default, it will create an error. If these is a field that may not exist, you can add the `optional=true` flag as part of the annotation value.
@Srivaralakshmi  I can see the whole paragraph has been rewritten. I am not sure which sentence that you want me to rewrite.

2022-06-24 07:05 UTC, Srivaralakshmi commented on docs/userguide/modules/exposing-binding-data/pages/adding-annotation.adoc
> +Sometimes a field may not exist in the target path. By default, it will create an error. If these is a field that may not exist, you can add the `optional=true` flag as part of the annotation value.
@baijum I meant this line: If these is a field that may not exist, you can add the `optional=true` flag as part of the annotation value.

But the request was only if my suggestion seems inaccurate technically.

2022-06-24 07:12 UTC, Srivaralakshmi requested changes
@baijum Left my suggestions. PTAL.Thanks!

2022-06-24 07:12 UTC, Srivaralakshmi commented on docs/userguide/modules/exposing-binding-data/pages/adding-annotation.adoc
> +. To enable {servicebinding-title} consider a new field in the annotations, provide the mapping by setting the `optional` flag value to `true`.
```suggestion
. To enable {servicebinding-title} consider a new field in the annotations, provide the mapping by setting the `optional` flag value to `true`:
```

2022-06-24 07:12 UTC, Srivaralakshmi commented on docs/userguide/modules/exposing-binding-data/pages/adding-annotation.adoc
> +* If you set the `optional` flag value to `false` and when the {servicebinding-title} is unable to find the target path, the annotations mapping fails.
```suggestion
* If you set the `optional` flag value to `false` and when the {servicebinding-title} is unable to find the target path, the Operator fails the annotations mapping.
```

2022-06-24 08:59 UTC, baijum commented on docs/userguide/modules/exposing-binding-data/pages/adding-annotation.adoc
> +Sometimes a field may not exist in the target path. By default, it will create an error. If these is a field that may not exist, you can add the `optional=true` flag as part of the annotation value.
The current text looks good to me. Please approve the PR if no more issues.

2022-06-27 09:15 UTC, Srivaralakshmi reviewed
@baijum Approved!

2022-06-27 09:16 UTC, Srivaralakshmi approved these changes
@baijum Approved!

2022-06-27 09:16 UTC, Srivaralakshmi commented
/lgtm

2022-07-11 06:07 UTC, baijum commented
/hold cancel

2022-07-11 06:08 UTC, baijum commented
/approve

2022-07-11 06:17 UTC, baijum commented
/test 4.11-acceptance

2022-07-11 08:50 UTC, baijum commented
/test 4.11-acceptance

2022-07-12 06:55 UTC, baijum commented
/test 4.8-acceptance

2022-07-12 09:17 UTC, merged