Support spec v1beta1 resources
redhat-developer/service-binding-operator pull request #1176
Opened 2022-06-21 19:52 UTC by sadlerap

Implements support for spec/v1beta1 resources.

# Changes

/kind enhancement

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#docs) 
  included if any changes are user facing
- [ ] [Tests](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#tests)
  included if any functionality added or changed. For bugfixes please include tests that can catch regressions
- [ ] All acceptance test scenarios included in the PR which verifies a bugfix or a requested feature reported by a non-member are tagged with `@external-feedback` tag.
- [ ] Follows the [commit message standard](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#commits)

2022-06-23 19:33 UTC, sadlerap commented
/retest

2022-06-24 20:02 UTC, sadlerap commented
/retest

2022-06-28 20:37 UTC, sadlerap commented
/retest

2022-07-20 18:47 UTC, sadlerap commented
/retest

2022-08-02 08:20 UTC, baijum requested changes

2022-08-02 21:46 UTC, sadlerap commented on PROJECT
> +  domain: operators.coreos.com
- I _think_ this was autogenerated by `kubebuilder`, not entirely certain.
- The `v1alpha3` entries also use `domain: operators.coreos.com`, I'm not entirely certain why.

2022-08-02 22:39 UTC, sadlerap commented on apis/spec/v1beta1/servicebinding_types.go
> +// +kubebuilder:object:root=true
According to [this](https://book.kubebuilder.io/reference/markers/crd.html), the default is indeed `Namespaced`.

Fixed in 0ceefae0.

2022-08-03 03:41 UTC, baijum commented on main.go
>  	specv1alpha3 "github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3"
We can remove these files:
- apis/spec/v1alpha3/clusterworkloadresourcemapping_webhook.go
- apis/spec/v1alpha3/clusterworkloadresourcemapping_webhook_test.go
- apis/spec/v1alpha3/servicebinding_webhook.go
- apis/spec/v1alpha3/servicebinding_webhook_test.go
- apis/spec/v1alpha3/suite_test.go

2022-08-09 22:06 UTC, sadlerap commented on main.go
>  	specv1alpha3 "github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3"
Fixed with 5c3f3e4.

2022-08-10 10:14 UTC, baijum commented
/lgtm
/approve

2022-08-10 10:18 UTC, merged