Add docs to set permissions due to Kubernetes bug
redhat-developer/service-binding-operator pull request #1191
Opened 2022-07-29 11:35 UTC by baijum

Fixes #1157

Signed-off-by: Baiju Muthukadan <baiju.m.mail@gmail.com>

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#docs) 
  included if any changes are user facing
- [ ] [Tests](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#tests)
  included if any functionality added or changed. For bugfixes please include tests that can catch regressions
- [ ] All acceptance test scenarios included in the PR which verifies a bugfix or a requested feature reported by a non-member are tagged with `@external-feedback` tag.
- [ ] Follows the [commit message standard](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#commits)

2022-07-29 15:25 UTC, sadlerap reviewed
With this fix, lgtm.
Would like a review from @Srivaralakshmi before merging.

2022-07-29 15:28 UTC, baijum commented on docs/userguide/modules/projecting-binding-data/pages/projecting-binding-data.adoc
> +**For using the binding data directory name to look up the binding data:** The {servicebinding-title} uses the `ServiceBinding` resource name (.`metadata.name`) as the binding data directory name, bu
@sadlerap 
This change was an accidental change. My editor removed the extra whitespace at the end of the lines.

I hope you must be checked the other note.

2022-08-03 12:17 UTC, sadlerap reviewed
Would like a review from @Srivaralakshmi as well.

2022-08-03 12:17 UTC, sadlerap commented on docs/userguide/modules/projecting-binding-data/pages/projecting-binding-data.adoc
> +The projected files gets the default permission.  If the service expects a specific permission, say `0600`, that's not possible due [a bug in Kubernetes](https://github.com/kubernetes/kubernetes/issu
I think I like this wording a bit better.
```suggestion
By default, the projected files get their permissions set to 0644.  {servicebinding-title} cannot set specific permissions due to [a bug in Kubernetes](https://github.com/kubernetes/kubernetes/issues/57923), which causes issues if the service expects a specific permission, such as `0600`.  As a workaround, the application can copy the file to `/tmp` directory and set the appropriate permissions.
```

2022-08-08 09:47 UTC, Srivaralakshmi requested changes
@baijum PTAL at the suggested changes. Thanks!

2022-08-08 09:47 UTC, Srivaralakshmi commented on docs/userguide/modules/projecting-binding-data/pages/projecting-binding-data.adoc
> +By default, the projected files get their permissions set to 0644.  {servicebinding-title} cannot set specific permissions due to [a bug in Kubernetes](https://github.com/kubernetes/kubernetes/issues
```suggestion
By default, the projected files get their permissions set to 0644.  {servicebinding-title} cannot set specific permissions due to [a bug in Kubernetes](https://github.com/kubernetes/kubernetes/issues/57923) that causes issues if the service expects specific permissions such as, `0600`.  As a workaround, you can modify the code of the program or the application that is running inside a workload resource to copy the file to the `/tmp` directory and set the appropriate permissions.
```

2022-08-08 10:23 UTC, fbm3307 commented
/lgtm

2022-08-08 10:25 UTC, fbm3307 commented
/approve

2022-08-08 10:30 UTC, baijum commented
/approve
/lgtm

2022-08-08 10:52 UTC, fbm3307 commented
/lgtm

2022-08-08 10:57 UTC, merged