WIP: Fix operator namespace usage in acceptance tests
redhat-developer/service-binding-operator pull request #1199
Opened 2022-08-10 13:52 UTC by pmacik

Signed-off-by: Pavel Macík <pavel.macik@gmail.com>

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#docs) 
  included if any changes are user facing
- [ ] [Tests](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#tests)
  included if any functionality added or changed. For bugfixes please include tests that can catch regressions
- [ ] All acceptance test scenarios included in the PR which verifies a bugfix or a requested feature reported by a non-member are tagged with `@external-feedback` tag.
- [ ] Follows the [commit message standard](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#commits)

2022-08-10 13:53 UTC, pmacik commented
/test all

2022-08-10 14:17 UTC, pmacik commented
/test all

2022-08-10 17:55 UTC, pmacik commented
/test all

2022-08-10 23:12 UTC, pmacik commented
/test all

2022-08-11 11:44 UTC, shruthihub approved these changes
looks good to me!

2022-08-11 11:56 UTC, shruthihub commented
/approved /lgtm

2022-08-11 15:24 UTC, baijum approved these changes
/lgtm

2022-08-11 15:31 UTC, baijum commented
> /approved /lgtm

@shruthihub These commands should be in separate lines.

2022-08-11 15:49 UTC, sadlerap requested changes
AIUI, if you want to call methods on a base class, you should be going through `super()` to preserve method resolution order.

2022-08-11 15:49 UTC, sadlerap commented on test/acceptance/features/steps/cloudnativepostgresoperator.py
> +        Operator.__init__(
```suggestion
        super().__init__(
```

2022-08-11 15:49 UTC, sadlerap commented on test/acceptance/features/steps/crunchypostgresoperator.py
> +            Operator.__init__(
```suggestion
            super().__init__(
```

2022-08-11 15:49 UTC, sadlerap commented on test/acceptance/features/steps/crunchypostgresoperator.py
> +            Operator.__init__(
```suggestion
            super().__init__(
```

2022-08-11 15:49 UTC, sadlerap commented on test/acceptance/features/steps/percona_mysql_operator.py
> +        Operator.__init__(
```suggestion
        super().__init__(
```

2022-08-11 15:49 UTC, sadlerap commented on test/acceptance/features/steps/rabbitmq_operator.py
> +        Operator.__init__(self, name=name)
```suggestion
        super().__init__(self, name=name)
```

2022-08-11 15:49 UTC, sadlerap commented on test/acceptance/features/steps/perconamongodboperator.py
> +        Operator.__init__(
```suggestion
        super().__init__(
```

2022-08-11 21:53 UTC, pmacik commented
> AIUI, if you want to call methods on a base class, you should be going through `super()` to preserve method resolution order.
> 
> Other than this, looks good.

Thx @sadlerap, good point. I've used your suggestions, PTAL

2022-08-12 10:09 UTC, pmacik commented
/test 4.12-acceptance

2022-08-12 10:44 UTC, pmacik commented
/test 4.12-acceptance

2022-08-16 05:01 UTC, baijum commented
/lgtm
/approve

2022-08-16 07:31 UTC, baijum commented
/retest

2022-08-16 07:52 UTC, pmacik commented
/retest

2022-08-16 10:02 UTC, merged