Fix #838
redhat-developer/service-binding-operator pull request #875
Opened 2021-02-16 06:30 UTC by akashshinde

### Motivation

<< Why this change is relevant, what's the "story" behind it? >>

### Changes

<< What has been changed in order to achieve "story's" objective? >>

### Testing

<< How to test those changes, reference implementation of unit/acceptance tests. >>

For further more details refer the CONTRIBUTING.md

2021-02-16 11:15 UTC, pedjak requested changes
please incorporate into this PR the test from https://github.com/redhat-developer/service-binding-operator/pull/842 and enable it, so that we can be sure that the bug has been fixed.

Please craft a proper commit message explain what was really done, also create a proper PR description.

2021-02-17 04:46 UTC, akashshinde commented on pkg/binding/model.go
> +
`sourceValue` is being used to figure out key fields from `ConfigMap`/`Secret`, and there few use cases where we require `sourceValue` along with `sourceKey`, ref: https://github.com/redhat-developer/service-binding-operator/blob/4f7892420a1382e3ea0ea2b0f0d2e08c8073d805/pkg/binding/spec_test.go#L253

2021-02-17 04:46 UTC, akashshinde commented on pkg/binding/model.go
> +	sourceValue := ""
not required, removed

2021-02-17 11:44 UTC, wtrocki commented
@akashshinde Amazing PR! Thank you so much for fix

2021-02-17 13:21 UTC, akashshinde commented on test/acceptance/features/bindAppToServiceUsingConfigMap.feature
> +@disabled-sourcekey
Need to remove this annotation

2021-02-17 14:02 UTC, pedjak commented
/lgtm
/approve

2021-02-17 14:16 UTC, pedjak commented
@wtrocki would you like to try out this PR and verify if the issue is solved before we merge it?

2021-02-17 15:35 UTC, wtrocki commented
This fixes problems with reflecting sourceKey but still have problem with binding 

```

    // This works after applying this PR but wasn't work before
    service.binding/password: >-
      path={.status.serviceAccountSecretName},objectType=Secret,sourceKey=client-secret

   // This doesn't work
   service.binding/bootstrapServer: 'path={.status.bootstrapServer.host}'

```

The second problem might be something to do with my setup as I see tests on operator doing the same.

2021-02-17 16:04 UTC, wtrocki approved these changes

2021-02-17 16:06 UTC, pedjak commented
/approve

2021-02-17 16:06 UTC, merged